services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      CHOKIDAR_USEPOLLING: true
      NODE_ENV: development
    command: ["npm", "run", "dev"]

  builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dist:/app/dist
    environment:
      NODE_ENV: production
    command: ["npm", "run", "build"]